/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as GoogleProfileRouteImport } from './routes/google-profile'
import { Route as HomesRouteImport } from './routes/homes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as QrRouteImport } from './routes/qr'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminGuideRouteImport } from './routes/admin.guide'
import { Route as AdminHomesRouteImport } from './routes/admin.homes'
import { Route as AgentsKitRouteImport } from './routes/agents.kit'
import { Route as AgentsSheetRouteImport } from './routes/agents.sheet'
import { Route as HomesIndexRouteImport } from './routes/homes.index'
import { Route as HomesSlugRouteImport } from './routes/homes.$slug'
import { Route as AdminHomesSlugRouteImport } from './routes/admin.homes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleProfileRoute = GoogleProfileRouteImport.update({
  id: '/google-profile',
  path: '/google-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesRoute = HomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideRoute = AdminGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomesRoute = AdminHomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => AdminRoute,
} as any)
const AgentsKitRoute = AgentsKitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsSheetRoute = AgentsSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => AgentsRoute,
} as any)
const HomesIndexRoute = HomesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomesRoute,
} as any)
const HomesSlugRoute = HomesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HomesRoute,
} as any)
const AdminHomesSlugRoute = AdminHomesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminHomesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/google-profile': typeof GoogleProfileRoute
  '/homes': typeof HomesRouteWithChildren
  '/portal': typeof PortalRoute
  '/qr': typeof QrRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/homes': typeof AdminHomesRouteWithChildren
  '/agents/kit': typeof AgentsKitRoute
  '/agents/sheet': typeof AgentsSheetRoute
  '/homes/$slug': typeof HomesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/homes/': typeof HomesIndexRoute
  '/admin/homes/$slug': typeof AdminHomesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/google-profile': typeof GoogleProfileRoute
  '/portal': typeof PortalRoute
  '/qr': typeof QrRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/homes': typeof AdminHomesRouteWithChildren
  '/agents/kit': typeof AgentsKitRoute
  '/agents/sheet': typeof AgentsSheetRoute
  '/homes/$slug': typeof HomesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/homes': typeof HomesIndexRoute
  '/admin/homes/$slug': typeof AdminHomesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ads': typeof AdsRoute
  '/agents': typeof AgentsRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRoute
  '/google-profile': typeof GoogleProfileRoute
  '/homes': typeof HomesRouteWithChildren
  '/portal': typeof PortalRoute
  '/qr': typeof QrRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/homes': typeof AdminHomesRouteWithChildren
  '/agents/kit': typeof AgentsKitRoute
  '/agents/sheet': typeof AgentsSheetRoute
  '/homes/$slug': typeof HomesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/homes/': typeof HomesIndexRoute
  '/admin/homes/$slug': typeof AdminHomesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ads'
    | '/agents'
    | '/contact'
    | '/crm'
    | '/google-profile'
    | '/homes'
    | '/portal'
    | '/qr'
    | '/whatsapp'
    | '/admin/guide'
    | '/admin/homes'
    | '/agents/kit'
    | '/agents/sheet'
    | '/homes/$slug'
    | '/admin/'
    | '/homes/'
    | '/admin/homes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ads'
    | '/agents'
    | '/contact'
    | '/crm'
    | '/google-profile'
    | '/portal'
    | '/qr'
    | '/whatsapp'
    | '/admin/guide'
    | '/admin/homes'
    | '/agents/kit'
    | '/agents/sheet'
    | '/homes/$slug'
    | '/admin'
    | '/homes'
    | '/admin/homes/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ads'
    | '/agents'
    | '/contact'
    | '/crm'
    | '/google-profile'
    | '/homes'
    | '/portal'
    | '/qr'
    | '/whatsapp'
    | '/admin/guide'
    | '/admin/homes'
    | '/agents/kit'
    | '/agents/sheet'
    | '/homes/$slug'
    | '/admin/'
    | '/homes/'
    | '/admin/homes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdsRoute: typeof AdsRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRoute
  GoogleProfileRoute: typeof GoogleProfileRoute
  HomesRoute: typeof HomesRouteWithChildren
  PortalRoute: typeof PortalRoute
  QrRoute: typeof QrRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-profile': {
      id: '/google-profile'
      path: '/google-profile'
      fullPath: '/google-profile'
      preLoaderRoute: typeof GoogleProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes': {
      id: '/homes'
      path: '/homes'
      fullPath: '/homes'
      preLoaderRoute: typeof HomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide': {
      id: '/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AdminGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homes': {
      id: '/admin/homes'
      path: '/homes'
      fullPath: '/admin/homes'
      preLoaderRoute: typeof AdminHomesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/agents/kit': {
      id: '/agents/kit'
      path: '/kit'
      fullPath: '/agents/kit'
      preLoaderRoute: typeof AgentsKitRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/sheet': {
      id: '/agents/sheet'
      path: '/sheet'
      fullPath: '/agents/sheet'
      preLoaderRoute: typeof AgentsSheetRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/homes/': {
      id: '/homes/'
      path: '/'
      fullPath: '/homes/'
      preLoaderRoute: typeof HomesIndexRouteImport
      parentRoute: typeof HomesRoute
    }
    '/homes/$slug': {
      id: '/homes/$slug'
      path: '/$slug'
      fullPath: '/homes/$slug'
      preLoaderRoute: typeof HomesSlugRouteImport
      parentRoute: typeof HomesRoute
    }
    '/admin/homes/$slug': {
      id: '/admin/homes/$slug'
      path: '/$slug'
      fullPath: '/admin/homes/$slug'
      preLoaderRoute: typeof AdminHomesSlugRouteImport
      parentRoute: typeof AdminHomesRoute
    }
  }
}

interface AdminHomesRouteChildren {
  AdminHomesSlugRoute: typeof AdminHomesSlugRoute
}

const AdminHomesRouteChildren: AdminHomesRouteChildren = {
  AdminHomesSlugRoute: AdminHomesSlugRoute,
}

const AdminHomesRouteWithChildren = AdminHomesRoute._addFileChildren(
  AdminHomesRouteChildren,
)

interface AdminRouteChildren {
  AdminGuideRoute: typeof AdminGuideRoute
  AdminHomesRoute: typeof AdminHomesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGuideRoute: AdminGuideRoute,
  AdminHomesRoute: AdminHomesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsKitRoute: typeof AgentsKitRoute
  AgentsSheetRoute: typeof AgentsSheetRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsKitRoute: AgentsKitRoute,
  AgentsSheetRoute: AgentsSheetRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface HomesRouteChildren {
  HomesSlugRoute: typeof HomesSlugRoute
  HomesIndexRoute: typeof HomesIndexRoute
}

const HomesRouteChildren: HomesRouteChildren = {
  HomesSlugRoute: HomesSlugRoute,
  HomesIndexRoute: HomesIndexRoute,
}

const HomesRouteWithChildren = HomesRoute._addFileChildren(HomesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdsRoute: AdsRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRoute,
  GoogleProfileRoute: GoogleProfileRoute,
  HomesRoute: HomesRouteWithChildren,
  PortalRoute: PortalRoute,
  QrRoute: QrRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
